AutoOps/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
from cmdb.views import account

# import xadmin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^xadmin/', xadmin.site.urls),
    url(r'^favicon.ico$', RedirectView.as_view(url=r'static/favicon.ico')),
    url(r'^$', account.IndexView.as_view(), name='index'),
    url(r'^login$', account.LoginView.as_view(), name='login'),
    url(r'^logout$', account.LogoutView.as_view(), name='logout'),

    url(r'^cmdb/', include('cmdb.urls')),
    url(r'^release/', include('release.urls')),

]

DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

cmdb/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/4/27 16:40
# @Author  : hardyxia
# @File    : urls.py
from django.conf.urls import url
from cmdb.views import instance, account, task

urlpatterns = [
    # 资产信息部分
    url(r'^instance$', instance.InstanceView.as_view(), name='instance'),
    url(r'^instance/detail/(\w+.*)$', instance.InstanceDetailView.as_view(), name='instance_detail'),
    # url(r'^instance/delete/(\w+.*)$', instance.InstanceDeleteView.as_view(), name='instance_delete'),
    url(r'^instance/delete$', instance.InstanceDeleteView.as_view(), name='instance_delete'),
    url(r'^instance/edit/(\w+.*)$', instance.InstanceEditView.as_view(), name='instance_edit'),
    url(r'^instance/add$', instance.InstanceAddView.as_view(), name='instance_add'),
    url(r'^instance/ssh$', instance.WebSSHView.as_view(), name='instance_ssh'),
    # url(r'^instance/ssh$', instance.web_ssh, name='instance_ssh'),

    # 登录用户
    url(r'^bind_user$', instance.BindUserView.as_view(), name='bind_user'),
    url(r'^bind_user/add$', instance.BindUserAddView.as_view(), name='bind_user_add'),
    url(r'^bind_user/detail/(\d+)$', instance.BindUserDetailView.as_view(), name='bind_user_detail'),
    # url(r'^bind_user/delete/(\d+)$', instance.BindUserDeleteView.as_view(), name='bind_user_delete'),
    url(r'^bind_user/delete$', instance.BindUserDeleteView.as_view(), name='bind_user_delete'),
    url(r'^bind_user/edit/(\d+)$', instance.BindUserEditView.as_view(), name='bind_user_edit'),

    # 常用URL
    url(r'^service_url$', instance.ServiceUrlView.as_view(), name='service_url'),
    url(r'^service_url/detail/(\d+)$', instance.ServiceUrlDetailView.as_view(), name='service_url_detail'),
    # url(r'^service_url/delete/(\d+)$', instance.ServiceUrlDeleteView.as_view(), name='service_url_delete'),
    url(r'^service_url/delete$', instance.ServiceUrlDeleteView.as_view(), name='service_url_delete'),
    url(r'^service_url/edit/(\d+)$', instance.ServiceUrlEditView.as_view(), name='service_url_edit'),
    url(r'^service_url/add$', instance.ServiceUrlAddView.as_view(), name='service_url_add'),

    # 任务相关
    url(r'^task_cmd$', task.TaskCMDView.as_view(), name='task_cmd'),
    url(r'^ssh_history$', task.SSHHistoryView.as_view(), name='ssh_history'),
    url(r'^task_file$', task.TaskFileTransfer.as_view(), name="task_file"),
    url(r'^task$', task.TaskView.as_view(), name="task"),
    url(r'^task_result$', task.TaskResultView.as_view(), name="task_result"),



]

cmdb/models.py
from django.db import models

from django.db import models
from DjangoUeditor.models import UEditorField
from django.contrib.auth.models import User

from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)


class IDC(models.Model):
    """机房信息"""
    name = models.CharField('机房', max_length=32)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'ops_idc'
        verbose_name_plural = "机房表"


class Region(models.Model):
    """可用区表"""
    id = models.CharField(verbose_name='区域编码', max_length=64, primary_key=True)
    name = models.CharField(verbose_name='区域名称', max_length=64, blank=True, null=True)
    endpoint = models.URLField(verbose_name='API地址', null=True, blank=True)
    idc = models.ForeignKey('IDC', verbose_name='机房', to_field='id', default=1, on_delete=models.CASCADE)

    def __str__(self):
        return '%s %s' % (self.idc, self.name,)

    class Meta:
        db_table = 'ops_region'
        verbose_name_plural = '可用区表'


class VPC(models.Model):
    """VPC表"""
    id = models.CharField(verbose_name='VPC ID', max_length=64, primary_key=True)
    name = models.CharField(verbose_name='VPC名称', max_length=64, blank=True, null=True)
    is_default = models.BooleanField(verbose_name='默认VPC', default=False)
    status_choices = (
        ('Available', '在线'),
        ('unAvailable', '离线'),
    )
    status = models.CharField(verbose_name='状态', choices=status_choices, max_length=16, default='Available')
    cidr_block = models.CharField(verbose_name='网段', max_length=64)
    region = models.ForeignKey('Region', verbose_name='区域', to_field='id')
    creation_time = models.CharField(verbose_name='创建时间', max_length=64, blank=True, null=True)
    description = UEditorField(verbose_name='内容', height=200, width=700,
                               default=u'', blank=True, imagePath="uploads/images/",
                               toolbars='besttome', filePath='uploads/files/')

    def color_status(self):
        if self.status == 'Available':
            color = 'red'
        else:
            color = 'green'
        return '<span style="color: %s ">%s</span>' % (color, self.get_status_display())

    color_status.allow_tags = True
    color_status.short_description = '状态'

    def __str__(self):
        return '%s【%s】' % (self.id, self.name)

    class Meta:
        db_table = 'ops_vpc'
        verbose_name_plural = 'VPC表'


class InstanceInfo(models.Model):
    '''主机实例信息 '''
    id = models.CharField(verbose_name='实例ID', max_length=64, primary_key=True)
    name = models.CharField(verbose_name='实例名称', max_length=64, null=True, blank=True)
    hostname = models.CharField(verbose_name='主机名', max_length=64, null=True, blank=True)
    key_pair_name = models.CharField(verbose_name='密钥', max_length=64, null=True, blank=True)
    os_type = models.CharField(verbose_name='系统类型', max_length=64, null=True, blank=True)
    os_name = models.CharField(verbose_name='系统名称', max_length=64, null=True, blank=True)
    cpu = models.SmallIntegerField(verbose_name='CPU数量', default=1)
    memory = models.IntegerField(verbose_name='总内存', default=2048)
    mac_address = models.CharField(verbose_name='MAC地址', max_length=64, null=True, blank=True)
    region = models.ForeignKey('Region', verbose_name='区域', )
    zone_id = models.CharField(verbose_name='可用区', max_length=64, null=True, blank=True)
    serial_number = models.CharField(verbose_name='序列号', max_length=64, null=True, blank=True)
    status = models.CharField(verbose_name='状态', max_length=64, null=True, blank=True)
    recyclable = models.BooleanField(verbose_name='可回收', default=False)
    security_group_ids = models.CharField(verbose_name='安全组ID', max_length=128, null=True, blank=True)
    eip_address = models.GenericIPAddressField(verbose_name='弹性IP地址', null=True, blank=True)
    public_ip_address = models.CharField(verbose_name='公网IP', max_length=64, null=True, blank=True)
    primary_ip_address = models.GenericIPAddressField(verbose_name='主IP地址')
    private_ip_address = models.GenericIPAddressField(verbose_name='私有IP地址', null=True, blank=True)
    port = models.IntegerField(verbose_name='SSH端口', default=22)
    creation_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    expired_time = models.DateTimeField(verbose_name='到期时间', auto_now_add=True)
    vpc = models.ForeignKey('VPC', verbose_name='所在VPC')
    idc = models.ForeignKey('IDC', verbose_name='服务商', default=1)
    enabled = models.BooleanField(default=True)
    description = models.TextField(verbose_name='备注', null=True, blank=True)
    bind_user = models.ForeignKey(to="BindUser", to_field='id', on_delete=models.SET_NULL, null=True,
                                  verbose_name='登陆用户', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'ops_instance_info'
        verbose_name_plural = '主机实例信息'


class InstanceGroup(models.Model):
    """主机实例组"""
    name = models.CharField(max_length=64, unique=True)
    bind_hosts = models.ManyToManyField("BindHost")

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'ops_instance_group'
        verbose_name_plural = "主机实例组"


class BindUser(models.Model):
    '''绑定的用户'''
    username = models.CharField(validators='用户名', max_length=32)
    ssh_type_choices = ((0, 'SSH/Password'), (1, 'SSH/Key'))
    ssh_type = models.SmallIntegerField(choices=ssh_type_choices, verbose_name='ssh类型', default=0)
    password = models.CharField(validators='密码', max_length=128, blank=True, null=True)
    comment = models.TextField(verbose_name='备注', blank=True, null=True)

    def __str__(self):
        return self.username

    class Meta:
        db_table = 'ops_bind_user'
        verbose_name_plural = '绑定的用户'


class BindHost(models.Model):
    """绑定远程主机和远程用户的对应关系"""
    host = models.ForeignKey("InstanceInfo")
    remote_user = models.ForeignKey("BindUser")

    def __str__(self):
        return "%s -> %s" % (self.host, self.remote_user)

    class Meta:
        unique_together = ("host", "remote_user")
        db_table = "ops_bind_host"
        verbose_name_plural = '主机与用户绑定关系'


class UserProfileManager(BaseUserManager):
    def create_user(self, username, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not username:
            raise ValueError('Users must have an username')

        user = self.model(

            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(

            username=username,
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class UserProfile(AbstractBaseUser, PermissionsMixin):
    # email = models.EmailField(verbose_name='email address', max_length=255, unique=True,blank=True, null=True)
    username = models.CharField(max_length=64, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(
        ('staff status'),
        default=False,
        help_text=('Designates whether the user can log into this admin site.'),
    )

    bind_hosts = models.ManyToManyField("BindHost", blank=True)
    host_groups = models.ManyToManyField("InstanceGroup", blank=True)

    objects = UserProfileManager()

    USERNAME_FIELD = 'username'

    # REQUIRED_FIELDS = ['username', ]

    def get_full_name(self):
        return self.username

    def get_short_name(self):
        # The user is identified by their email address
        return self.username

    def __str__(self):  # __unicode__ on Python 2
        return self.username

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    class Meta:
        verbose_name_plural = "用户"


class Session(models.Model):
    '''生成用户操作session id '''
    user = models.ForeignKey('UserProfile')
    bind_host = models.ForeignKey('BindHost')
    tag = models.CharField(max_length=128, default='n/a')
    closed = models.BooleanField(default=False)
    cmd_count = models.IntegerField(default=0)  # 命令执行数量
    stay_time = models.IntegerField(default=0, help_text="每次刷新自动计算停留时间", verbose_name="停留时长(seconds)")
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '<id:%s user:%s bind_host:%s>' % (self.id, self.user.email, self.bind_host.host)

    class Meta:
        verbose_name = '审计日志'
        verbose_name_plural = '审计日志'


class Task(models.Model):
    """批量任务记录表"""
    user = models.ForeignKey("UserProfile")
    task_type_choices = ((0, 'cmd'), (1, 'file_transfer'))
    task_type = models.SmallIntegerField(choices=task_type_choices)
    content = models.TextField(verbose_name="任务内容")
    login_ip = models.CharField(verbose_name="操作IP", max_length=64, blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s %s" % (self.task_type, self.content)

    class Meta:
        db_table = "ops_task"
        verbose_name_plural = '任务记录'


class TaskLogDetail(models.Model):
    task = models.ForeignKey("Task")
    bind_host = models.ForeignKey("BindHost")
    result = models.TextField()
    status_choices = ((0, 'success'), (1, 'failed'), (2, 'init'))
    status = models.SmallIntegerField(choices=status_choices)

cmdb/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, logout, login
from django.conf import settings
import os, re, json
from web import models
from backend.task_manager import MultiTaskManger

from backend import audit


# Create your views here.

def json_date_handler(obj):
    if hasattr(obj, 'isoformat'):
        return obj.strftime("%Y-%m-%d %T")


@login_required
def dashboard(request):
    return render(request, 'index.html')


def acc_login(request):
    error_msg = ''

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)

            return redirect("/")

        else:
            error_msg = "Wrong username or password!"
    return render(request, "login.html", {'error_msg': error_msg})


def acc_logout(request):
    logout(request)

    return redirect("/login/")


@login_required
def webssh(request):
    return render(request, 'web_ssh.html')


@login_required
def user_audit(request):
    log_dirs = os.listdir(settings.AUDIT_LOG_DIR)

    return render(request, 'user_audit.html', locals())


@login_required
def audit_log_date(request, log_date):
    log_date_path = "%s/%s" % (settings.AUDIT_LOG_DIR, log_date)
    log_file_dirs = os.listdir(log_date_path)
    session_ids = [re.search("\d+", i).group() for i in log_file_dirs]

    session_objs = models.Session.objects.filter(id__in=session_ids)

    return render(request, 'user_audit_file_list.html', locals())


@login_required
def multitask_cmd(request):
    return render(request, "multitask_cmd.html")


@login_required
def multitask_file_transfer(request):
    return render(request, 'multitask_file_transfer.html')


@login_required
def multitask_result(request):
    task_id = request.GET.get('task_id')
    task_obj = models.Task.objects.get(id=task_id)
    task_log_results = list(task_obj.tasklogdetail_set.values('id', 'result', 'status', 'start_date', 'end_date'))

    return HttpResponse(json.dumps(task_log_results, default=json_date_handler))


@login_required
def multitask(request):
    print("--->", request.POST)
    task_data = json.loads(request.POST.get('task_data'))
    print("--->selcted hosts", task_data)

    task_obj = MultiTaskManger(request)
    selected_hosts = list(task_obj.task.tasklogdetail_set.all().values('id', 'bind_host__host__ip_addr',
                                                                       'bind_host__host__hostname',
                                                                       'bind_host__remote_user__username'))

    return HttpResponse(
        json.dumps({'task_id': task_obj.task.id, 'selected_hosts': selected_hosts})
    )


@login_required
def audit_log_detail(request, log_date, session_id):
    log_date_path = "%s/%s" % (settings.AUDIT_LOG_DIR, log_date)
    log_file_path = "%s/session_%s.log" % (log_date_path, session_id)

    log_parser = audit.AuditLogHandler(log_file_path)
    cmd_list = log_parser.parse()

    return render(request, "user_audit_detail.html", locals())

cmdb/views/container.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/5/24 11:53
# @Author  : hardyxia
# @File    : container.py
from django.shortcuts import render, redirect, resolve_url, reverse
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password, check_password
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator


class LogoutView(View):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(LogoutView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        auth.logout(request)
        return HttpResponseRedirect(reverse('login'))

templates/cmdb/bind_user.html
{% extends 'common/base.html' %}

{% block title %}系统用户{% endblock %}

{% block page-header %}系统用户{% endblock %}

{% block page-header-info %}查看{% endblock %}

{% block page-content %}
    <div id="sample-table-2_wrapper" class="dataTables_wrapper" role="grid">
        <div class="row">
            {% include 'common/pg_num.html' %}
            <div class="col-sm-6">
                <div class="dataTables_filter" id="sample-table-2_filter">
                    <a href="{% url 'bind_user_add' %}">
                        <button class="btn-info " type="button" style="float: right"> 添加</button>
                    </a>
                </div>


            </div>
        </div>

        <table id="sample-table-2" class="table table-striped table-bordered table-hover dataTable"
               aria-describedby="sample-table-2_info">
            <thead>
            <tr role="row">

                {% for row in title %}
                    <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1"
                        colspan="1" aria-label="Domain: activate to sort column ascending"
                        style="width: 168px;">{{ row }}
                    </th>
                {% endfor %}
                <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1"
                    colspan="1" aria-label="Domain: activate to sort column ascending" style="width: 168px;">操作
                </th>
            </tr>
            </thead>


            <tbody role="alert" aria-live="polite" aria-relevant="all">
            {% for row in response %}
                <tr class="odd"  nid="{{ row.id }}">

                    <td class=" "><a href="{% url 'bind_user_detail' row.id %}">{{ row.username }}</a></td>

                    <td class=" ">{% if row.password %}{{ row.password }}{% endif %} </td>
                    <td class=" ">{{ row.get_ssh_type_display }}</td>
                    <td class=" ">{% if row.comment %}{{ row.comment }}{% endif %}</td>
                    <td class=" ">
                        <div class="visible-md visible-lg hidden-sm hidden-xs action-buttons">

                            <a class="green" href="{% url 'bind_user_edit' row.id %}" title="编辑">
                                <i class="icon-edit bigger-130"></i>
                            </a>

                            <a class="red bind_user_del" href="#" title="删除">
                                <i class="icon-trash bigger-130"></i>
                            </a>
                        </div>

                        <div class="visible-xs visible-sm hidden-md hidden-lg">
                            <div class="inline position-relative">
                                <button class="btn btn-minier btn-yellow dropdown-toggle" data-toggle="dropdown">
                                    <i class="icon-caret-down icon-only bigger-120"></i>
                                </button>

                                <ul class="dropdown-menu dropdown-only-icon dropdown-yellow pull-right dropdown-caret dropdown-close">
                                    <li>
                                        <a href="#" class="tooltip-info" data-rel="tooltip" title=""
                                           data-original-title="View">
                                    <span class="blue">
                                        <i class="icon-zoom-in bigger-120"></i>
                                    </span>
                                        </a>
                                    </li>

                                    <li>
                                        <a href="#" class="tooltip-success" data-rel="tooltip" title=""
                                           data-original-title="Edit">
                                    <span class="green"><i class="icon-edit bigger-120">
                                    </i>
                                    </span>
                                        </a>
                                    </li>

                                    <li>
                                        <a href="#" class="tooltip-error" data-rel="tooltip" title=""
                                           data-original-title="Delete">
                                    <span class="red">
                                        <i class="icon-trash bigger-120"></i>
                                    </span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
        {% include 'common/paginator.html' %}
    </div>


{% endblock %}

{% block js %}
    <script>
        $(function () {

            $(document).on('click', '.bind_user_del', function () {
                var nid = $(this).parent().parent().parent().attr('nid');
                console.log(nid);
                swal({
                    title: "你确定删除",
                    text: "你将无法恢复",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "确定",
                    closeOnConfirm: false
                }, function () {
                    $.ajax({
                        headers: {"X-CSRFToken": '{{ csrf_token }}'},
                        url: "{% url 'bind_user_delete' %}",
                        type: 'POST',
                        data: {'nid': nid},
                        success: function (data) {
                            var obj = JSON.parse(data);
                            if (obj.status) {
                                swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                    window.location.reload();
                                })
                            } else {
                                swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                            }
                        }
                    });


                });

            });


        });
    </script>
{% endblock %}

templates/cmdb/bind_user_add.html
{% extends 'common/base.html' %}

{% block title %}添加用户{% endblock %}

{% block page-header %}系统用户{% endblock %}

{% block page-header-info %}添加

{% endblock %}

{% block page-content %}
    <form class="form-horizontal" role="form" method="post">
        {% csrf_token %}
        <div class="form-horizontal"></div>
        <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right" for="form-input-readonly">用户名</label>
            <div class="col-sm-9">
                <input type="text" class="col-xs-10 col-sm-5" id="form-field-1" name="username">
            </div>
        </div>


        <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">SSH类型</label>
            <div class="col-sm-9">
                <input type="text" id="form-field-1" class="col-xs-10 col-sm-5" name="ssh_type"
                       placeholder="请输入0或1,0:密码,1:密钥">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">密码</label>

            <div class="col-sm-9">
                <input type="text" id="form-field-1" class="col-xs-10 col-sm-5" name="password"
                       placeholder="选择密钥方式可不填">
            </div>
        </div>
        <!--
        <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">端口</label>

            <div class="col-sm-9">
                <input type="text" id="form-field-1" class="col-xs-10 col-sm-5" name="port" >
            </div>
        </div>
        -->
        <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">备注</label>

            <div class="col-sm-9">
                <input type="text" id="form-field-1" class="col-xs-10 col-sm-5" name="comment">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right" for="form-field-1" style="margin-left: 5%">
                <span style="color: red;">{{ error }}</span>
            </label>

        </div>


        <div class="clearfix form-actions">
            <div class="col-md-offset-3 col-md-9">
                <button class="btn btn-info" type="submit">
                    <i class="icon-ok bigger-110"></i>
                    保存
                </button>
                &nbsp; &nbsp; &nbsp;
                <a href="{% url 'bind_user' %}">
                    <button class="btn" type="button">
                        <i class="icon-undo bigger-110"></i>
                        取消
                    </button>
                </a>
            </div>
        </div>
    </form>
{% endblock %}

templates/cmdb/bind_user_detail.html
{% extends 'common/base.html' %}

{% block title %}用户详情{% endblock %}

{% block page-header %}系统用户{% endblock %}

{% block page-header-info %}查看用户名{{ response.0.username }} 详情

    <a href="{% url 'bind_user_delete' response.0.id %}">
        <button class="btn btn-danger" type="button" style="float: right"> 删除</button>
    </a>
    <a href="{% url 'bind_user_edit' response.0.id %}">
        <button class="btn btn-info" type="button" style="float: right"> 编辑</button>
    </a>
{% endblock %}

{% block page-content %}
    <form class="form-horizontal">

        <div class="form-horizontal"></div>
        <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right" for="form-input-readonly">用户名</label>
            <div class="col-sm-9">
                <input readonly="" type="text" class="col-xs-10 col-sm-5" id="form-input-readonly"
                       value="{{ response.0.username }}">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right" for="form-input-readonly">SSH类型</label>
            <div class="col-sm-9">
                <input readonly="" type="text" class="col-xs-10 col-sm-5" id="form-input-readonly"
                       value="{{ response.0.get_ssh_type_display }}">
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right" for="form-input-readonly">密码</label>
            <div class="col-sm-9">
                <input readonly="" type="text" class="col-xs-10 col-sm-5" id="form-input-readonly"
                       value="{{ response.0.password }}">
            </div>
        </div>
        <!--
        <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right" for="form-input-readonly">端口</label>
            <div class="col-sm-9">
                <input readonly="" type="text" class="col-xs-10 col-sm-5" id="form-input-readonly"
                       value="{{ response.0.port }}">
            </div>
        </div>
-->
        <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right" for="form-input-readonly">备注</label>
            <div class="col-sm-9">
                <input readonly="" type="text" class="col-xs-10 col-sm-5" id="form-input-readonly"
                       value="{% if response.0.comment %}{{ response.0.comment }}{% endif %}">
            </div>
        </div>


    </form>
{% endblock %}

templates/cmdb/index.html
{% extends 'common/base.html' %}

{% block title %}首页{% endblock %}

{% block page-content %}
    <h1 >首页还没想好放什么东西</h1>
{% endblock %}

templates/cmdb/multitask_file_transfer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>